version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: leave-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: leave_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: leave-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

  app:
    build: ./leave-back
    container_name: leave-back
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      
  leave-app:
    build: ./leave-app
    container_name: leave-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  pgdata:
  